server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://106.14.44.65:3306/person?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456789123wzx
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  influx:
    url: http://146.56.200.122:8086
    user: root
    password: 123456789123wzx
    database: aiops
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.wzxlq.entity
management:
  endpoint:
    health:
      show-details: always
    httptrace:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
      cors:
        allowed-origins: '*'
        allowed-methods: GET,POST
  metrics:
    export:
      influx:
        db: aiops
        uri: http://146.56.200.122:8086
        user-name: root
        password: 123456789123wzx
        enabled: true
        connect-timeout: 1s
        read-timeout: 10s
        auto-create-db: true
        step: 1m
        num-threads: 2
        consistency: one
        compressed: true
        batch-size: 1000
    web:
      server:
#        auto-time-requests: true
        request:
          autotime:
            enabled: true
    tags:
      app: ${server.address}
      port: ${server.port}
